"use client";

import React, { useState, DragEvent, ChangeEvent } from "react";

type EngineStatus = "idle" | "running" | "complete" | "error";

interface HighlightConfig {
  targetLengthSec: number;
  aggression: number;
  pace: number;
  includeAudio: boolean;
  slowmoKeyMoments: boolean;
}

export default function Home() {
  const [clips, setClips] = useState<File[]>([]);
  const [isDragging, setIsDragging] = useState(false);

  const [length, setLength] = useState(45);
  const [aggression, setAggression] = useState(8);
  const [pace, setPace] = useState(7);
  const [includeAudio, setIncludeAudio] = useState(true);
  const [slowmo, setSlowmo] = useState(true);

  const [engineStatus, setEngineStatus] = useState<EngineStatus>("idle");
  const [progress, setProgress] = useState(0);
  const [statusLabel, setStatusLabel] = useState("Idle");
  const [statusMsg, setStatusMsg] = useState(
    "Drop raw clips to start building a hype edit."
  );
  const [outputUrl, setOutputUrl] = useState<string | null>(null);

  function formatSize(bytes: number): string {
    const mb = bytes / (1024 * 1024);
    return `${mb.toFixed(1)} MB`;
  }

  function estimateDuration(files: File[]): string {
    if (!files.length) return "—";
    const totalMB =
      files.reduce((sum, f) => sum + f.size, 0) / (1024 * 1024);
    const minutes = totalMB / 200; // rough guess: 1 min per 200MB raw
    if (minutes <= 0.5) return "< 30s (rough guess)";
    return `${(Math.round(minutes * 10) / 10).toString()} min (rough guess)`;
  }

  function handleAddFiles(fileList: FileList | null) {
    if (!fileList) return;
    const accepted = Array.from(fileList).filter((file) =>
      file.type.startsWith("video/")
    );
    if (!accepted.length) return;

    setClips((prev) => [...prev, ...accepted]);
  }

  function handleDrop(e: DragEvent<HTMLDivElement>) {
    e.preventDefault();
    e.stopPropagation();
    setIsDragging(false);
    if (e.dataTransfer?.files) {
      handleAddFiles(e.dataTransfer.files);
    }
  }

  function handleDragOver(e: DragEvent<HTMLDivElement>) {
    e.preventDefault();
    e.stopPropagation();
    setIsDragging(true);
  }

  function handleDragLeave(e: DragEvent<HTMLDivElement>) {
    e.preventDefault();
    e.stopPropagation();
    setIsDragging(false);
  }

  function handleFileInputChange(e: ChangeEvent<HTMLInputElement>) {
    handleAddFiles(e.target.files);
    e.target.value = "";
  }

  function handleRemoveClip(index: number) {
    setClips((prev) => prev.filter((_, i) => i !== index));
  }

  function resetEngine() {
    setEngineStatus("idle");
    setProgress(0);
    setStatusLabel("Idle");
    setStatusMsg("Drop raw clips to start building a hype edit.");
    setOutputUrl(null);
  }

  async function handleGenerate() {
    if (!clips.length) return;

    setEngineStatus("running");
    setProgress(8);
    setStatusLabel("Preparing");
    setStatusMsg(
      "Packaging clips and settings for the highlight engine…"
    );
    setOutputUrl(null);

    const formData = new FormData();
    clips.forEach((file, i) => {
      formData.append("clips", file, file.name || `clip_${i}.mp4`);
    });

    const config: HighlightConfig = {
      targetLengthSec: length,
      aggression,
      pace,
      includeAudio,
      slowmoKeyMoments: slowmo,
    };

    formData.append("config", JSON.stringify(config));

    const endpoint = "/api/generate-highlight";

    // Fake front-end progress while waiting on the backend
    let fakeProgress = 10;
    const interval = setInterval(() => {
      fakeProgress = Math.min(fakeProgress + 5, 85);
      setProgress(fakeProgress);
      setStatusLabel("Processing");
      setStatusMsg(
        "Analyzing clips for big plays, clean strikes, and hype moments…"
      );
      if (fakeProgress >= 85) clearInterval(interval);
    }, 400);

    try {
      const res = await fetch(endpoint, {
        method: "POST",
        body: formData,
      });

      clearInterval(interval);

      if (!res.ok) {
        throw new Error("Non-200 response");
      }

      const data = await res.json();
      const videoUrl = data.videoUrl as string | undefined;

      setProgress(100);
      setStatusLabel("Complete");
      setStatusMsg("Highlight reel generated by backend.");
      setEngineStatus("complete");
      setOutputUrl(videoUrl || "#");
    } catch (err) {
      console.error(err);
      clearInterval(interval);
      setProgress(100);
      setStatusLabel("Backend missing");
      setStatusMsg(
        "Could not reach /api/generate-highlight. Deploy your serverless function or connect your AI/video pipeline."
      );
      setEngineStatus("error");
      setOutputUrl("#");
    }
  }

  const totalBytes = clips.reduce((sum, f) => sum + f.size, 0);

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 flex justify-center">
      <div className="max-w-5xl w-full mx-4 my-6 rounded-3xl border border-slate-700/60 bg-gradient-to-br from-slate-950 via-slate-950 to-slate-950 shadow-2xl shadow-slate-950/90 p-5 md:p-7">
        {/* Header */}
        <header className="flex flex-col md:flex-row md:items-center md:justify-between gap-4 border-b border-slate-800 pb-4">
          <div>
            <div className="flex items-center gap-3 flex-wrap">
              <h1 className="text-xl md:text-2xl font-semibold tracking-[0.18em] uppercase">
                Sports Hype Builder
              </h1>
              <span className="inline-flex items-center gap-2 rounded-full border border-slate-600/80 px-3 py-1 text-[0.68rem] uppercase tracking-[0.16em] text-slate-300 bg-slate-900/70">
                <span className="h-2 w-2 rounded-full bg-emerald-400 shadow-[0_0_12px_rgba(74,222,128,0.9)]" />
                AI Highlight Engine
              </span>
            </div>
            <p className="mt-2 text-xs md:text-sm text-slate-400 max-w-xl">
              Drop raw clips from <span className="text-emerald-400">any sport</span> — MMA, football, basketball,
              soccer, boxing and more — and generate social-ready hype edits that
              showcase your biggest moments.
            </p>
          </div>
          <div className="flex flex-wrap gap-2 justify-start md:justify-end text-[0.7rem] text-slate-300">
            <span className="px-3 py-1 rounded-full border border-slate-600/80 bg-slate-900/70 uppercase tracking-[0.14em]">
              Multi-clip Upload
            </span>
            <span className="px-3 py-1 rounded-full border border-slate-600/80 bg-slate-900/70 uppercase tracking-[0.14em]">
              KO / Big-Play First
            </span>
            <span className="px-3 py-1 rounded-full border border-slate-600/80 bg-slate-900/70 uppercase tracking-[0.14em]">
              Vercel Ready
            </span>
          </div>
        </header>

        {/* Main Grid */}
        <main className="mt-5 grid gap-4 md:grid-cols-[1.5fr_1fr]">
          {/* Left: Upload panel */}
          <section className="relative rounded-2xl border border-slate-700/80 bg-slate-950/80 shadow-xl shadow-slate-950/80 p-4 overflow-hidden">
            <div className="pointer-events-none absolute -top-20 -left-24 h-64 w-64 rounded-full bg-emerald-500/10 blur-3xl" />
            <div className="relative space-y-3">
              <div className="flex items-start justify-between gap-3">
                <div>
                  <p className="text-[0.72rem] uppercase tracking-[0.16em] text-slate-400">
                    Source Clips
                  </p>
                  <p className="text-xs text-slate-400 mt-1">
                    Fight footage, game tape, training clips—drop it all. The engine
                    will hunt for clean hits, big plays, and highlight moments.
                  </p>
                </div>
                <span className="inline-flex items-center gap-2 rounded-full border border-slate-600/80 bg-slate-900/80 px-3 py-1 text-[0.7rem] uppercase tracking-[0.15em] text-slate-300">
                  <span className="h-1.5 w-1.5 rounded-full bg-emerald-400 shadow-[0_0_10px_rgba(74,222,128,0.9)]" />
                  Raw Feed
                </span>
              </div>

              {/* Upload zone */}
              <div
                onDrop={handleDrop}
                onDragOver={handleDragOver}
                onDragLeave={handleDragLeave}
                onDragEnd={handleDragLeave}
                className={[
                  "mt-2 flex cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed px-4 py-5 text-center transition-all",
                  isDragging
                    ? "border-emerald-400 bg-emerald-500/10"
                    : "border-slate-600/70 bg-slate-900/70 hover:border-emerald-400/70 hover:bg-slate-900"
                ].join(" ")}
                onClick={() =>
                  document.getElementById("file-input")?.click()
                }
              >
                <div className="mb-2 flex h-11 w-11 items-center justify-center rounded-full border border-slate-600/80 text-xl">
                  ⬆️
                </div>
                <div className="text-sm">
                  Drop{" "}
                  <span className="font-semibold text-emerald-400">
                    MP4 / MOV / MKV
                  </span>{" "}
                  here
                </div>
                <div className="mt-1 text-xs text-slate-400">
                  Or click to browse and select multiple clips.
                </div>
                <div className="mt-2 text-[0.7rem] text-slate-500">
                  Tip: Keep original quality. Long games, full fights & whole
                  quarters are welcome.
                </div>
                <div className="mt-3 flex w-full items-center justify-between text-[0.72rem] text-slate-300">
                  <span>
                    Clips queued:{" "}
                    <span className="text-emerald-400 font-semibold">
                      {clips.length}
                    </span>
                  </span>
                  <span>
                    Total size:{" "}
                    <span className="text-emerald-400 font-semibold">
                      {formatSize(totalBytes)}
                    </span>
                  </span>
                </div>
              </div>

              <input
                id="file-input"
                type="file"
                accept="video/*"
                multiple
                className="hidden"
                onChange={handleFileInputChange}
              />

              {/* File list */}
              <div className="mt-3 max-h-60 overflow-y-auto rounded-xl border border-slate-800 bg-slate-950/90">
                {clips.length === 0 ? (
                  <div className="px-4 py-5 text-center text-xs text-slate-500">
                    No clips loaded yet. Drop raw footage to start building a hype
                    edit.
                  </div>
                ) : (
                  <ul className="divide-y divide-slate-800 text-xs">
                    {clips.map((file, idx) => (
                      <li
                        key={idx}
                        className="flex items-center justify-between gap-3 px-3 py-2.5"
                      >
                        <div className="min-w-0">
                          <div className="truncate text-[0.78rem]">
                            {file.name}
                          </div>
                          <div className="mt-1 flex flex-wrap gap-2 text-[0.68rem] text-slate-400">
                            <span className="rounded-full border border-slate-700 px-2 py-0.5">
                              {file.type || "video/*"}
                            </span>
                            <span className="rounded-full border border-slate-700 px-2 py-0.5">
                              Clip #{idx + 1}
                            </span>
                          </div>
                        </div>
                        <div className="flex items-center gap-3 flex-shrink-0">
                          <span className="text-[0.7rem] text-slate-400">
                            {formatSize(file.size)}
                          </span>
                          <button
                            onClick={() => handleRemoveClip(idx)}
                            className="rounded-full px-2 py-1 text-[0.75rem] text-slate-400 hover:bg-red-500/15 hover:text-red-400 transition-colors"
                            title="Remove clip"
                          >
                            ✕
                          </button>
                        </div>
                      </li>
                    ))}
                  </ul>
                )}
              </div>

              <div className="mt-2 flex items-center justify-between text-[0.7rem] text-slate-400">
                <span>
                  Estimated input length:{" "}
                  <span className="text-slate-200">
                    {estimateDuration(clips)}
                  </span>
                </span>
                <span className="hidden sm:inline">
                  Best results: 1080p, 30–60 FPS.
                </span>
              </div>
            </div>
          </section>

          {/* Right: Settings & generation */}
          <section className="relative rounded-2xl border border-slate-700/80 bg-slate-950/80 shadow-xl shadow-slate-950/80 p-4 overflow-hidden">
            <div className="pointer-events-none absolute -top-24 -right-24 h-64 w-64 rounded-full bg-blue-500/15 blur-3xl" />
            <div className="relative space-y-3">
              <div className="flex items-start justify-between gap-3">
                <div>
                  <p className="text-[0.72rem] uppercase tracking-[0.16em] text-slate-400">
                    Highlight Engine
                  </p>
                  <p className="mt-1 text-xs text-slate-400">
                    Tune how aggressive, dense, and fast-paced you want the edit.
                  </p>
                </div>
                <span className="inline-flex items-center gap-2 rounded-full border border-slate-600/80 bg-slate-900/80 px-3 py-1 text-[0.7rem] uppercase tracking-[0.15em] text-slate-300">
                  <span className="h-1.5 w-1.5 rounded-full bg-emerald-400 shadow-[0_0_10px_rgba(74,222,128,0.9)]" />
                  Edit Profile
                </span>
              </div>

              {/* Sliders */}
              <div className="space-y-3 mt-2">
                <SliderRow
                  label="Highlight length (sec)"
                  subtitle="Target duration of the final hype edit."
                  value={length}
                  min={15}
                  max={120}
                  onChange={setLength}
                  display={(v) => `${v}s`}
                />

                <SliderRow
                  label="Aggression"
                  subtitle="Weight towards impact: KOs, dunks, tackles, big swings."
                  value={aggression}
                  min={1}
                  max={10}
                  onChange={setAggression}
                  display={(v) => `${v}/10`}
                />

                <SliderRow
                  label="Pace"
                  subtitle="Clip density & tempo. Higher = faster, more cuts."
                  value={pace}
                  min={1}
                  max={10}
                  onChange={setPace}
                  display={(v) => `${v}/10`}
                />
              </div>

              {/* Toggles */}
              <div className="mt-3 space-y-2.5">
                <ToggleRow
                  label="Include live audio"
                  description="Prioritize game commentary, crowd reactions, and corner audio where possible."
                  checked={includeAudio}
                  onChange={setIncludeAudio}
                />
                <ToggleRow
                  label="Slow-mo big moments"
                  description="Automatic slow motion on KOs, dunks, breakaways, and highlight swings."
                  checked={slowmo}
                  onChange={setSlowmo}
                />
              </div>

              {/* Helper */}
              <p className="mt-2 text-[0.7rem] text-slate-500">
                Note: This UI calls{" "}
                <code className="rounded bg-slate-900 px-1.5 py-0.5 text-[0.7rem] text-emerald-300 border border-slate-700">
                  /api/generate-highlight
                </code>
                . Connect this endpoint to your AI/video pipeline (FFmpeg +
                model/service) inside a Vercel serverless function.
              </p>

              {/* Actions */}
              <div className="mt-3 space-y-3">
                <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                  <div className="flex flex-wrap items-center gap-2">
                    <button
                      onClick={handleGenerate}
                      disabled={!clips.length || engineStatus === "running"}
                      className={`inline-flex items-center gap-2 rounded-full px-4 py-2 text-[0.78rem] font-semibold uppercase tracking-[0.16em] transition-all ${
                        !clips.length || engineStatus === "running"
                          ? "bg-emerald-500/30 text-slate-900/60 cursor-not-allowed shadow-none"
                          : "bg-gradient-to-r from-emerald-500 to-lime-400 text-slate-950 shadow-lg shadow-emerald-500/60 hover:shadow-emerald-500/80 hover:-translate-y-px"
                      }`}
                    >
                      <span>⚡</span>
                      <span>Generate Highlight</span>
                    </button>
                    <button
                      type="button"
                      onClick={() => {
                        setClips([]);
                        resetEngine();
                      }}
                      className="inline-flex items-center gap-2 rounded-full border border-slate-600 bg-slate-900 px-3 py-1.5 text-[0.72rem] text-slate-300 hover:border-slate-400 hover:bg-slate-900/80 transition-colors"
                    >
                      🧹 Clear clips
                    </button>
                  </div>
                  <div className="text-right text-[0.7rem] text-slate-400">
                    <div className="inline-flex items-center gap-2 rounded-full border border-slate-700 bg-slate-900/80 px-3 py-1">
                      <span className="h-1.5 w-1.5 rounded-full bg-emerald-400 shadow-[0_0_8px_rgba(74,222,128,0.9)]" />
                      <span className="uppercase tracking-[0.16em]">
                        Runtime Engine
                      </span>
                    </div>
                    <div className="mt-1">
                      Status:{" "}
                      <span className="text-emerald-400 font-medium">
                        {engineStatus === "idle"
                          ? "Idle"
                          : engineStatus === "running"
                          ? "Running"
                          : engineStatus === "complete"
                          ? "Complete"
                          : "Error"}
                      </span>
                    </div>
                  </div>
                </div>

                {/* Progress */}
                {(engineStatus === "running" ||
                  engineStatus === "complete" ||
                  engineStatus === "error") && (
                  <div className="rounded-xl border border-slate-700 bg-slate-950/90 px-3 py-3 text-[0.75rem] space-y-2">
                    <div className="h-1.5 w-full rounded-full bg-slate-900 overflow-hidden">
                      <div
                        className={`h-full rounded-full transition-all ${
                          engineStatus === "error"
                            ? "bg-gradient-to-r from-red-500 via-orange-500 to-red-500"
                            : "bg-gradient-to-r from-emerald-400 via-lime-400 to-orange-400"
                        }`}
                        style={{ width: `${progress}%` }}
                      />
                    </div>
                    <div className="flex items-center justify-between gap-3 flex-wrap">
                      <div className="inline-flex items-center gap-2 rounded-full border border-slate-700 bg-slate-900/80 px-2.5 py-1">
                        <span
                          className={`h-1.5 w-1.5 rounded-full ${
                            engineStatus === "error"
                              ? "bg-red-400 shadow-[0_0_10px_rgba(248,113,113,0.9)]"
                              : "bg-emerald-400 shadow-[0_0_10px_rgba(74,222,128,0.9)]"
                          }`}
                        />
                        <span className="uppercase tracking-[0.14em] text-[0.68rem]">
                          {statusLabel}
                        </span>
                      </div>
                      <div className="text-right text-[0.7rem] text-slate-400">
                        {statusMsg}
                      </div>
                    </div>
                  </div>
                )}

                {/* Output */}
                {outputUrl && (
                  <div className="flex items-center justify-between gap-3 rounded-xl border border-dashed border-slate-700 bg-slate-950/80 px-3 py-2.5 text-[0.75rem]">
                    <div className="text-slate-200">
                      Highlight ready.{" "}
                      <span className="text-slate-400">
                        Download or preview the reel.
                      </span>
                    </div>
                    <div className="flex items-center gap-2">
                      <a
                        href={outputUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-emerald-400 hover:underline"
                      >
                        ⬇️ Download highlight
                      </a>
                      <span className="rounded-full border border-slate-700 px-2 py-0.5 text-[0.7rem] text-slate-400">
                        ~{length}s hype edit
                      </span>
                    </div>
                  </div>
                )}
              </div>
            </div>
          </section>
        </main>
      </div>
    </div>
  );
}

interface SliderRowProps {
  label: string;
  subtitle: string;
  value: number;
  min: number;
  max: number;
  onChange: (v: number) => void;
  display: (v: number) => string;
}

function SliderRow({
  label,
  subtitle,
  value,
  min,
  max,
  onChange,
  display,
}: SliderRowProps) {
  return (
    <div className="flex items-center justify-between gap-3">
      <div className="text-xs">
        <div className="text-[0.78rem] text-slate-200">{label}</div>
        <div className="mt-0.5 text-[0.7rem] text-slate-400">
          {subtitle}
        </div>
      </div>
      <div className="flex flex-1 items-center gap-3 max-w-[190px]">
        <input
          type="range"
          min={min}
          max={max}
          value={value}
          onChange={(e) => onChange(Number(e.target.value))}
          className="h-1.5 w-full accent-emerald-400"
        />
        <div className="w-12 text-right text-[0.75rem] text-slate-200">
          {display(value)}
        </div>
      </div>
    </div>
  );
}

interface ToggleRowProps {
  label: string;
  description: string;
  checked: boolean;
  onChange: (v: boolean) => void;
}

function ToggleRow({ label, description, checked, onChange }: ToggleRowProps) {
  return (
    <button
      type="button"
      onClick={() => onChange(!checked)}
      className="flex w-full items-center gap-3 rounded-xl border border-slate-700 bg-slate-950/70 px-3 py-2 text-left hover:border-emerald-400/70 hover:bg-slate-900/80 transition-colors"
    >
      <div
        className={[
          "relative h-5 w-9 rounded-full border flex-shrink-0 transition-colors",
          checked
            ? "border-emerald-400 bg-emerald-500/30"
            : "border-slate-600 bg-slate-900",
        ].join(" ")}
      >
        <div
          className={[
            "absolute top-0.5 h-4 w-4 rounded-full bg-slate-950 shadow-sm transition-transform",
            checked ? "translate-x-4" : "translate-x-0.5",
          ].join(" ")}
        />
      </div>
      <div className="text-[0.78rem]">
        <div className="text-slate-200">{label}</div>
        <div className="text-[0.7rem] text-slate-400 mt-0.5">
          {description}
        </div>
      </div>
    </button>
  );
}
